### ISSUE TITLE
Exile v0.9.8 update

### ISSUE THREAD

**Issue by Gummibeer** [WolfkillArcadia/AdvancedBanking#2]
With the update to Exile v0.9.8 the whole money/poptab system has changed. The variable `ExileClientPlayerMoney` is no more in use - instead there are `player getVariable ["ExileMoney",0];` and `player getVariable ["ExileLocker", 0];`. Cause of this nothing is working anymore.

**Comment by WolfkillArcadia** [comment]
Please review my comment on Exile forums.
http://www.exilemod.com/topic/11466-closed-advanced-banking/?do=findComment&comment=103962 

If you would like to make it compatible, feel free to. But I see no need to do it as that Exile has this functionality by default now.

**Comment by Gummibeer** [comment]
Ok, I thought so. Even if your GUI was absolutely amazing!
