### ISSUE TITLE
Large ints not displaying correctly

### ISSUE THREAD

**Issue by WolfkillArcadia** [WolfkillArcadia/AdvancedBanking#2]
Large intergers when converted to string will parse oddly. 
New version has problem when transfering huge ammount of money between client and server, because arma can not show correctly huge integers as strings. Integer 7952790 becomes 7.95279e+06.  Client will have 0 instead of 7952790.

**Comment by Gr8z** [comment]
Is it wise to add a check to all transfer function to limit it to numbers under 999,999 ?

**Comment by WolfkillArcadia** [comment]
The issue is that I just did a testing on this, the server, client, and the database had no issues with these, transferred 2 billion perfectly fine. I notice that you have some high priced stuff on your server, so let me know if players run into issues transferring high amount of money. Until then, I'm going to pend this as waiting for more information

**Comment by Gr8z** [comment]
Never had an issue with large amounts before the banking system. And Had no reports of money loss after the Bank Implementation. 

The only problem is to display such large numbers in game. Here is a workaround :

```
fnc_numberToString =
{
    _number = _this;
    _str = "";
    if (_number % 1 == 0) then
    {
        while { _number > 0 } do
        {
            _digit = floor (_number % 10);
            _str = (str _digit) + _str;
            _number = floor (_number / 10);
        };
    }
    else
    {
        _decimals = _number % 1;
        _decimals = _decimals * 1000000;
        _number = floor _number;
        _str = _number call MTP_fnc_numberToString;
        _str = _str + "." + str _decimals;
    };
    
    _str;
};
```

**Comment by WolfkillArcadia** [comment]
It's all good, we have a fix in place for when shared Banking is released. Thank you none the less.

**Comment by TheeMrshix** [comment]
GR8 you can just use call BIS_fnc_numberText

**Comment by WolfkillArcadia** [comment]
Fixed next update. 
/closed
